config/routes.rb
Rails.application.routes.draw do
 
  # the page root
  root 'products#index'

  # routes for Devise and Omniauth
  devise_for :users
  resources :carts 
    resources :products do
    member do
      get :add_to_cart
    end
  end  

  # routes for Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  # routes for locale change
  get 'sessions/:locale', to: "sessions#switch", as: :sessions

  # routes for Users
  resources :users

  # route for User Sign Out
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :signout
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    
    user ||= User.new # guest user (not logged in)
    
    can :manage, User do |u|
      user.id == u.id
    end
    
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
    
    has_many :cartships
    has_many :products, through: :cartships
    
    #for testing purposes
    def total_price
        cartships.map{|cartship| cartship.product.price * cartship.quantity}.sum
    end
end

app/models/cartship.rb
class Cartship < ActiveRecord::Base
    belongs_to :product
    belongs_to :carts 
end

app/models/product.rb
class Product < ActiveRecord::Base
   validates :title, :presence => true
   validates :price, :presence => true
   has_many :cartships
  # belongs_to :cart, through: :cartships
   
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  include TokenAuthenticatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
         :omniauth_providers => [:facebook, :twitter, :instagram]

  before_save :ensure_authentication_token

  mount_uploader :image, ImageUploader

  def self.from_omniauth(auth)
    where(provider: auth[:provider], uid: auth[:uid]).first_or_initialize.tap do |user|
      user = User.load_user_from_omniauth(user, auth)
    end
  end

  private

    def self.load_user_from_omniauth(user, auth)
      user.provider = auth.provider
      user.uid = auth.uid
      user.oauth_token = auth.credentials.token
      user.email = auth.info.email if user.email.blank?
      user.email = auth.info.nickname + "@#{auth.provider}.com" if user.email.blank?
      user.password = Devise.friendly_token[0,20] if user.password.blank?
      user.remote_image_url = auth.info.image.gsub('http://','https://') if user.remote_image_url.blank?
      return user
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_filter :set_locale
  skip_before_action :verify_authenticity_token, if: :json_request?

  def json_request?
    request.format.json?
  end

  def current_user
    User.find_by_authentication_token(params[:auth_token]) || ( warden.authenticate(scope: :user) rescue nil)
  end

  def remember_token
    data = User.serialize_into_cookie @user
    "#{data.first.first}-#{data.last}"
  end

  def after_sign_in_path_for(resource)
    root_path
  end

  private

  def authenticate_user_from_token!
    user_token = params[:user_token].presence
    user       = user_token && User.find_by_authentication_token(user_token.to_s)
    if user
      sign_in user, store: false
    end
  end

  def invalid_credentials
    render json: {}, status: 401
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :image, :password_confirmation) }
  end

  def set_locale
    I18n.locale = session[:locale] || I18n.default_locale
    session[:locale] = I18n.locale
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
def show
    @cart =  Cart.find(params[:id])
    
end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    
    def index
        @products = Product.all.order('created_at DESC')
        
    end
    
    def add_to_cart
        #if there is no cart create one
        if session[:cart_id].blank?
            cart= Cart.create(status: 'pending')
            session[:cart_id]= cart.id
        else
            #if the cart is present find it
            cart=Cart.find(session[:cart_id])
        end
        #find the specific product per say and equate to the cart 
    product= Product.find(params[:id])
    #then fill the cart using cartship values which inherits it from the products and increments the quantity atrribute in the model cartship
    cart.cartships.create(product_id: product.id , quantity: 1)
    redirect_to cart
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def switch
    session[:locale] = params[:locale]
    redirect_to_back_or_root
  end

  private

  def redirect_to_back_or_root(default = root_path)
    if request.env["HTTP_REFERER"].present? && request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
      redirect_to :back
    else
      redirect_to root_url
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def edit
    @user = current_user
  end

  def update()
    prepare_params
    if @user.update_attributes(user_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit( :email, :password, :password_confirmation, :image, :remove_image)
    end

    def load_user
      user = User.find(params[:id])
    end

    def prepare_params
      if params[:user][:password].blank? && \
        params[:user][:password_confirmation].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def add_error(message, status)
    if status == "error"
      flash.now[:error] = message if message.present?
    elsif status == "success"
      flash.now[:success] = message if message.present?
    else
      flash.now[:notice] = message if message.present?
    end
  end
  
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.erb
<table class="table">
    <thead class="thead-inverse">
        <tr>
            
        <th>Brand</th>
        <th>Product name</th>
        <th>Quantity </th>
        <th>Price</th>
        <th>total</th>
   <!--     </tr>
   </thead>-->
    <%  @cart.cartships.each do |cart| %>
          </tr>
   </thead>
    <tbody>
        <tr>
    <th scope ="row"><%=cart.product.brand.upcase! %></th>
    <td><%= cart.product.title.capitalize! %></td>
    <td><%= cart.quantity %></td>
    <td><%= number_to_currency(cart.product.price) %></td>
    <td><%= number_to_currency(cart.product.price * cart.quantity) %></td>
    </tr>
    </tbody>
<% end %>
 <tr span="col-3">
        <td>Total</td><td></td><td></td><td></td>
        <td><%= number_to_currency(@cart.total_price) %></td>
    </tr>
</table>
<%= link_to 'back', products_path,class: "btn btn-success" %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tech-store
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    = favicon_link_tag 'favicon.ico'
        
  %body{class: params[:controller].gsub("/", "-")}

    .container-fluid.margin-top-100
      = yield

      %script{type: "text/javascript", 'data-turbolinks-eval'=>false}
        var string = "#{(j (yield :scripts))}";
        eval(string);
        window.starterkitrails.shared.init();
    = render 'shared/flash_notice'

app/views/layouts/mail.html.haml
%html{style: "height: 100%"}
  %head
    %meta{content: "text/html; charset=utf-8", "http-equiv" => "Content-Type"}
    %title Email StarterKit
  %body{style: "margin: 0; padding: 0; height: 100%; background-color: white"}
    %table{cellpadding: "0", cellspacing: "0", style: "width: 100%; height: 100%; border-spacing: 0"}
      %tr
        %td{style: "width: 10%; background-color: #e8e8e8"}
        %td{style: "width: 80%; background-color: #FDFEFF"}
          %table{cellpadding: "0", cellspacing: "0",cellpadding: "0", cellspacing: "0",  style: "width: 100%; height: 100%"}
            %tr
              %td{colspan: "3", style: "height: 25%"}

            %tr
              %td{style: "width: 15%;"}
              %td
                %table{cellpadding: "0", cellspacing: "0",style: "width: 100%; height: 100%"}
                  %tr{style: "height: 25%"}
                    %td{style: "background-color: #E8E8E8; border: 1px solid #00929f; width: 93%"}
                      %h1{style: "font-family: Helvetica, Arial, sans-serif; font-size: 24px; color: #244a67; padding-left: 20px"}
                        = yield :head
                        %span{style: "font-weight: normal"}
                          = yield :mail
                  %tr{style: "width: 100%; height: 75%"}
                    %td{style: "border: 1px solid #00929f"}
                      .p_content{style: "font-family: Helvetica, Arial, sans-serif ; font-size: 16px; margin-top: 0px; margin-bottom: 5%; padding: 0px; color: #244a67; padding-left: 20px"}
                        = yield :content
                    %td
              %td{style: "width: 15%;"}
            %tr
              %td{colspan: "3", style: "height: 25%"}

        %td{style: "width: 10%; background-color: #e8e8e8"}

app/views/products/index.html.erb
<div class= "row">
<!--making the products align on one -->
    <% @products.each do |product| %>
    
        <div class="col-sm-4 text-center">
            <%= image_tag product.image,class: "img-rounded",style: "max-height:130px"%><br>
            <hr>
            <em><%= product.brand.upcase! %></em><br><hr>
            <%= product.title.capitalize! %><br><hr>
           $<%= product.price %><br><hr>
            <%= link_to 'add to cart',add_to_cart_product_path(product) %>
        
        </div>
    <% end-%>
 </div>

app/views/shared/_flash_notice.html.haml
- if flash[:notice].present? || flash[:alert].present? || flash[:error].present?
  - [:notice, :alert, :error].each do |key|
    - next if flash[key].blank?
    .flash-container
      .flash{class: key}
        %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×
        = flash[key]

      - flash[key] = nil

app/views/shared/_languages.html.haml
= link_to_unless_current "En", sessions_path("en")

app/views/shared/_logo.html.haml
.form-group
  %i.fa.fa-star
  PRE-EMPLOYMENT-APP

app/views/users/edit.html.haml
.row
  .col-md-4.col-md-offset-4
    = form_for @user, html: {multipart: true } do |f|
      - add_error(@user.errors.full_messages.to_sentence, 'alert') if @user.errors.any?

      .form-group.input-group.input-group-lg
        %span.input-group-addon
          %i.fa.fa-user
        = f.email_field :email, autofocus: true, placeholder: "#{t ".email"}", autocomplete: "off", class: "form-control"

      .form-group.input-group.input-group-lg
        %span.input-group-addon
          %i.fa.fa-lock
        = f.password_field :password, autocomplete: "off", placeholder: "#{t ".new_password"}", class: "form-control"

      .form-group.input-group.input-group-lg
        %span.input-group-addon
          %i.fa.fa-lock
        = f.password_field :password, autocomplete: "off", placeholder: "#{t ".confirm_new_password"}", class: "form-control"

      .form-group
        .fileupload.fileupload-new{data: {provides: 'fileupload'}}
          .fileupload-preview.thumbnail.thumb-preview{style: "width: 80px; height: 77px"}
            - if @user.try(:image).present?
              = image_tag @user.image
            - else
              = image_tag "fallback/avatar.png"
          %div
            %span.btn.btn-file.btn-default.btn-sm
              %span.fileupload-new
                %span.glyphicon.glyphicon-picture
                = t ".image"
              %span.fileupload-exists
                %span.glyphicon.glyphicon-open
                = t '.change'
              = f.file_field :image
            = link_to "#", class: "btn fileupload-exists btn-danger btn-sm", data: {dismiss: 'fileupload'} do
              %span.glyphicon.glyphicon-remove
              = t '.remove'

      - if @user.try(:image).present?
        .form-group
          .checkbox
            %label
              = f.check_box :remove_image
              = t ".remove_image"

      .form-group
        = f.submit (t ".button_update"), class: "btn btn-success full-width"

      .form-group
        = link_to (t ".button_sign_out"), signout_path, class: "btn btn-default"